### ISSUE TITLE
godmode ban (bug)

### ISSUE THREAD

**Issue by victorTrofelli** [TigoDevelopment/TigoAntiCheat#12]
I ended up finding a bug here from godmode, when the person enters the server automatically she is banned, even if she is not cheating

**Comment by ThymonA** [comment]
Is this for one person or does it occur to more than one person?
You speak especially in her form, does this problem only occur with female characters?
Maybe then I can figure out what the problem is. I don't have this problem myself at all.

**Comment by victorTrofelli** [comment]
I don't know, I haven't tested with other people, but just when the anticheat enters it detects how godmode and bans you on time.

**Comment by CruelAlpha** [comment]
It can be another script conflicting, the script works fine on my end. Haven't tried with latest update however

**Comment by ThymonA** [comment]
Do you have a script that gives people extra healing or something like that?

**Comment by ThymonA** [comment]
After 14 days, no reply. Issue closed
