### ISSUE TITLE
Banning triggers from more mod menus

### ISSUE THREAD

**Issue by ghost** [TigoDevelopment/TigoAntiCheat#14]
Hi love the anticheat great work

i have a big list of menus if you would like them to see if you could ban triggers from them please let me know thanks.

**Comment by kapiziak** [comment]
I can share my big list of menus too. Just add me on Discord: KapiziaK#7601

**Comment by ThymonA** [comment]
That would be great, so we can add more triggers to the list.

**Comment by ThymonA** [comment]
All found events have been added, and the client event has also been added to the anticheat.
I would look in the future to see if I can find more things and add more.
For now this issue is done, because menus have been added.
