### ISSUE TITLE
Players get banned when banking

### ISSUE THREAD

**Issue by ADRNALN** [TigoDevelopment/TigoAntiCheat#17]
After my players go to the bank to withdraw or deposit money they get banned since it is calling on bank:withdraw and bank:deposit. My temporary fix was removing this code from the anti-cheat itself and it has fixed the issue.

Is there something specific we're supposed to change for this feature?
The script I'm using: https://github.com/NewWayRP/new_banking

**Comment by iSentrie** [comment]
Smart enough to remove feature from AC, but too dumb to change the event on banking? Do you even read the readme's?

**Comment by ThymonA** [comment]
What you can do is to rename events in the bank script by putting e.g. tiimon_ before every event.
**Example**:
-- Before
```lua
RegisterNetEvent('bank:result')
AddEventHandler('bank:result', function(type, message)
	SendNUIMessage({type = 'result', m = message, t = type})
end)
```
-- After
```lua
RegisterNetEvent('tiimon_bank:result')
AddEventHandler('tiimon_bank:result', function(type, message)
	SendNUIMessage({type = 'result', m = message, t = type})
end)
```
Then the problem is solved and your players won't be banned anymore.

**Comment by ADRNALN** [comment]
I looked at the even prefixes and skimmed over that one even though it's at the top. I have fixed it since!
