### ISSUE TITLE
banned while noclipping

### ISSUE THREAD

**Issue by ADRNALN** [TigoDevelopment/TigoAntiCheat#18]
I was just flying around in noclip on my server and I got banned for 
Reason: Player had modified there jump height
I was using vMenu's noclip feature

**Comment by iSentrie** [comment]
So?

**Comment by ThymonA** [comment]
I don't know if you have set permissions in vMenu, but don't forget to add the following to your `server.cfg`
```cfg
add_ace group.{your group} tigoanticheat.bypass allow
```
This ensures that everyone who belongs to this group cannot be banned by this anticheat.

**Comment by ADRNALN** [comment]
Yep, I've implemented this now, thanks!
