### ISSUE TITLE
some idea ..

### ISSUE THREAD

**Issue by ExpMero** [TigoDevelopment/TigoAntiCheat#23]
### Hello, there are 2 ideas if you can do it
**1**: block any using of executor, if anyone tries to execute Lua code, detect them 
**2**: anti dump for server, there are many cheats right now can dump server and decrypt client files
if u can detect it it will be best anti-cheat

**Comment by ThymonA** [comment]
Countering a dumper is difficult / impossible. This simply because scripts have already been dumped before they are executed. Because of this, a script cannot do this.

Blocking an executor is also difficult to prevent, as some executors block client files before they are loaded at all.
