### ISSUE TITLE
High ms?

### ISSUE THREAD

**Issue by Aero-Codes** [TigoDevelopment/TigoAntiCheat#25]
Hello sometimes i'm getting 0.40+ms sometimes in game using resmon 1 or only me having this problem?

**Comment by ThymonA** [comment]
Have you installed the latest possible version of `TigoAntiCheat`?

**Comment by Aero-Codes** [comment]
Yea it is the latest version i'm using i get 0.40 ms and its only 2 people online inside

**Comment by ThymonA** [comment]
That's on the high side, I'll try to see if I can find a possible memory leak.

**Comment by Aero-Codes** [comment]
nice, when you plan to release your v1.1.0 ? with nuke and explosion anti cheat ?

**Comment by ThymonA** [comment]
Do you have a name for me from your server where I can trace where this high ms came from? You can also send it via discord if you'd prefer.
https://discordapp.com/users/636509961375055882

**Comment by Aero-Codes** [comment]
i tried to message you, long time ago you are not replying

Mac Gaming#2446 - here is my discord

**Comment by ThymonA** [comment]
Contact via Discord, indicated that he must temporarily disable `objects.lua`.
Go make a fix for this in the coming days
