### ISSUE TITLE
False postive, dragging people out of cars

### ISSUE THREAD

**Issue by Jer2168** [TigoDevelopment/TigoAntiCheat#27]
When we kill a person inside and drag them out, the AC bans the person being dragged out for god mode.

**Comment by ThymonA** [comment]
This is something I haven't been able to reproduce myself. Would you give me a list of scripts that makes it possible to dragging people around

**Comment by Jer2168** [comment]
Only thing I got is SEM_Interaction menu. That's all I got for drag, etc.

**Comment by ThymonA** [comment]
I checked the script and only command `loadout` or `clear` are a possibility which would cause a player be banned for godmode.
Your specified script has nothing that would lead to this ban when a player is dragged.

What I can advise you is to look at the following functions `SetEntityHealth` and `AddArmourToPed` and in which script they are all called.

If you don't find anything that could lead to this ban, you can also disable the check by not loading the file in the `fxmanifest.lua`.

https://github.com/TigoDevelopment/TigoAntiCheat/blob/5a623b216216fe12d46b0d1d5dd739e084329f2d/fxmanifest.lua#L60
