### ISSUE TITLE
On enter ban

### ISSUE THREAD

**Issue by iglesiiaskeviin** [TigoDevelopment/TigoAntiCheat#29]
When im enter to the server , the anticheat banned me for execut a command 'getSharedObject'

**Comment by Richards0nd** [comment]
You need to change all ESX event names
just read the documentation right to understand how it works.

**Comment by TigoDevelopment** [comment]
Then you did not follow the instructions in `README.md`. I would recommend that you read that before installing `TigoAntiCheat`
