### ISSUE TITLE
error when try ban a staff with bypass

### ISSUE THREAD

**Issue by mindiw01** [TigoDevelopment/TigoAntiCheat#30]
![image](https://user-images.githubusercontent.com/58794615/78836634-e32cb700-79c8-11ea-9f94-bbcb894a9393.png)

help pls?

**Comment by Richards0nd** [comment]
Then you did not follow the instructions in `README.md`. I would recommend that you read that before installing `TigoAntiCheat`

**Comment by mindiw01** [comment]
The functions that a user uses (without being superadmin, since the superadmin has bypass) ban it correctly, once I change everything to tac, it doesn't ban it. It is what I do not understand, if it works, because it gives a random error, that we do not even know when it happens.

**Comment by Richards0nd** [comment]
What is the specific reason for the ban? (which shows in the ban file)

**Comment by mindiw01** [comment]
I mean, when it gives that error, it doesn't ban the user who should ban. (Try banning but if condition returns null/nil)

https://github.com/TigoDevelopment/TigoAntiCheat/blob/master/server/main.lua#L85-L104 (Line 86)

**Comment by Richards0nd** [comment]
This is probably why you must have done something wrong when installing TigoAntiCheat, as I am using it, and I have not had any problems until today!
Try to redo all the steps ... I recommend you do it as follows:

Instead of changing everything you have: `TiggerServer(esx_` or `TigerEvent(esx_` ... as mentioned in the documentation.
You in each of your scripts, the following:
`esx_` to `tac_`
`esx:` for `tac:`

It doesn't have to be exactly tac, it can be anything you want to put ...
for example: `BLUE_` or `DARK:`

**Comment by mindiw01** [comment]
I am using this to move all events from esx:/esx_ to tac:/tac_, could you tell me if it is ok at least?

Python script: https://gist.github.com/mindiw01/ad907151ac361883f8000b6535805fb4
And in the bat/bash script I use this:
```
replace.py "esx:" "tac:"
replace.py "esx_" "tac_"
pause
```

**Comment by Richards0nd** [comment]
Try changing to another event name ...
Other than `TAC`
try to put: `eessxx` or any other name that comes into your mind

**Comment by mindiw01** [comment]
https://mindiw.me/img/Y1O9OTBQ.png

other error :/

**Comment by Richards0nd** [comment]
Try to reinstall TigoAntiCheat.
Without making any changes, just download the stable version and put it on your server.

**Comment by mindiw01** [comment]
doesnt work /:

**Comment by ThymonA** [comment]
I've just made some changes, and if all goes well, your error should be gone. If this is not the case, I would like a new screenshot of the error due to possible of new lines.

**Comment by mindiw01** [comment]
Thanks. I will test!

**Comment by mindiw01** [comment]
After 4 days testing, its working perfectly. Thanks!
