### ISSUE TITLE
Hi TigoAntiCheat random ban me

### ISSUE THREAD

**Issue by HUNaGyerek** [TigoDevelopment/TigoAntiCheat#31]

**Comment by ThymonA** [comment]
I need more information, do you have a server or are you banned as a player?

**Comment by HUNaGyerek** [comment]
This is my Own server and when i start Tigo and reconnect i get banned

2020. ápr. 13. 8:02 de. ezt írta ("TigoDEV" <notifications@github.com>):

**Comment by ThymonA** [comment]
Would you send me a copy of your ban? Please without identifiers
