### ISSUE TITLE
Banned by no reason was given.

### ISSUE THREAD

**Issue by h03ein72** [TigoDevelopment/TigoAntiCheat#35]
Hi, I changed every events that you said and renamed prefix events (ex. bank:transfer to hos_bank:transfer) but when a player(not an admin) joined the server immediately (banned by no reason was given).

![Untitled](https://user-images.githubusercontent.com/9111099/80181333-e2776000-8619-11ea-9666-69a6d83e1681.png)

+ He also clear his caches and try again but nothing happened. 
+ I checked the old version (1.1) and It's worked fine.

Thanks.

**Comment by ThymonA** [comment]
I'll check for you right away to see what might be causing this problem.

**Comment by ThymonA** [comment]
This problem should be solved

**Comment by h03ein72** [comment]
Thank your for your help.
