### ISSUE TITLE
[BUG] EnableCountryWhitelist

### ISSUE THREAD

**Issue by Richards0nd** [TigoDevelopment/TigoAntiCheat#37]
**Describe the bug**
When someone is trying to enter the server, there is an error, and he cannot enter, he is frozen in the AntiCheat verification screen ...
![image](https://user-images.githubusercontent.com/45667828/80193727-ba730700-85ef-11ea-9821-c6565682cb18.png)

This presents an error on the console
```
Conectando: Richardson Douglas
SCRIPT ERROR: @TigoAntiCheat/server/functions.lua:821: attempt to index a nil value
> handler (@TigoAntiCheat/server/common.lua:389)
```
![image](https://user-images.githubusercontent.com/45667828/80193704-b21acc00-85ef-11ea-9e92-b11143773a6a.png)

I realized that this error only happens when AntiCheat.EnableCountryWhitelist is set to TRUE
When it is FALSE, he says that my IP is from the USA, and my IP is from BRAZIL, and I don't use any VPS ...
![image](https://user-images.githubusercontent.com/45667828/80193848-e1c9d400-85ef-11ea-884b-2bbf6e969c5c.png)
He somehow identifies that the IP is in the USA ...
![image](https://user-images.githubusercontent.com/45667828/80193873-ee4e2c80-85ef-11ea-8bc2-679557a2a08f.png)

If I set the config to FALSE (the EnableCountryWhitelist), it won't let me in because it says the IP is from the USA ...

The operating system used on the server is LINUX

**When the option is set to false and still has countries released**
![image](https://user-images.githubusercontent.com/45667828/80194755-3b7ece00-85f1-11ea-8aed-950592413d18.png)

![image](https://user-images.githubusercontent.com/45667828/80194686-1f7b2c80-85f1-11ea-95e8-e7eda890baf1.png)

**Comment by ThymonA** [comment]
```json
{
"ip":"170.84.157.242",
"countryCode":"BR",
"countryName":"Brazil",
"asn":264998,
"isp":"SQUID",
"block":0,
"hostname":"170-84-157-242.squidtelecom.com.br"
}
```
As for your IP, it's just listed correctly in the API. This means that there may be a proxy or server between you and the FXServer.
Unfortunately, I cannot reproduce or trace the error you have recorded, because changes was made after you downloaded it

**Comment by Richards0nd** [comment]
But there is also the issue that the system is marked as false, and even then does not let me enter the server, as I said earlier.
![image](https://user-images.githubusercontent.com/45667828/80194755-3b7ece00-85f1-11ea-8aed-950592413d18.png)

![image](https://user-images.githubusercontent.com/45667828/80194686-1f7b2c80-85f1-11ea-95e8-e7eda890baf1.png)

**Comment by ThymonA** [comment]
But your IP isn't blocked by the whitelist, but the VPN Check

**Comment by Richards0nd** [comment]
Yes, indeed. Too stupid of me, I hadn't paid attention. But anyway, in the old version of AntiCheat, I left it enabled and was not blocked by the VPN system, and my IP address did not change. So much so that I tested using the old and current version, the old one released me, and the current one did not release me, and in both cases VPN Check is enabled.
