### ISSUE TITLE
Bug, banlist

### ISSUE THREAD

**Issue by victorTrofelli** [TigoDevelopment/TigoAntiCheat#8]
how can I get rid of my server? Even taking off the banlist will not

**Comment by ThymonA** [comment]
What you need to do is remove the ban from the list, then do the command `/anticheat reload` (in console or authorized player) and people are off the ban list.
If you have automatic update of identifiers enabled you should also consider disabling them or removing the matching identifiers.

**Comment by victorTrofelli** [comment]
I'Il try, thx

**Comment by victorTrofelli** [comment]
even if I remove myself from the list and put false in the updateidentifiers I am being banned.

sorry for my English*

**Comment by ThymonA** [comment]
Would you check that one of your identifiers isn't already on the ban list?
`IP`, `XBL LIVE`, `MICROSOFT ACCOUNT`, `FIVEM LICENSE`, `STEAM ID`
Based on these identifiers, he checks if someone is banned.
___
Then you have to do command `/anticheat reload` to make sure the banlist is reloaded.
